services:
#Dynamically generated target services
    target1:
        build: .
        command: ["node", "app.js", "target/"]
        volumes: ["./output/target1:/usr/src/app/output"]
        profiles: ["app"]
        networks: [myapp]
    target2:
        build: .
        command: ["node", "app.js", "target/"]
        volumes: ["./output/target2:/usr/src/app/output"]
        profiles: ["app"]
        networks: [myapp]

    splitter:
        build: .
        command: ["node", "app.js", "splitter/"]
        depends_on:
          - target1
          - target2
        profiles: ["app"]
        networks: [myapp]

    agent:
        build: .
        command: ["node", "app.js", "agent/"]
        depends_on: [splitter]
        profiles: ["app"]
        networks: [myapp]
  
    tests:
        build: 
            context: .
            dockerfile: Dockerfile.test
        volumes: ["./output:/tests/output"]
        profiles: ["tests"]
        networks: [myapp]


networks:
  myapp:
    driver: bridge

