name: Cribl Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      
      - name: Start app
        run: |
          docker compose -f docker-compose.dynamic.yml --profile=app up -d --build

      - name: Run tests
        run: |
          docker compose -f docker-compose.dynamic.yml run --rm --build tests pytest -v
      
      - name: Tear down containers
        if: always()
        run: |
          docker compose -f docker-compose.dynamic.yml --profile=app --profile=test down --remove-orphans
