name: Cribl Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      
      - name: Start app
        run: |
          docker compose --profile=app up -d --build

      - name: Run tests
        run: |
          docker compose run --rm --profile=tests tests -v
      
      - name: Tear down containers
        if: always()
        run: |
          docker compose --profile=tests --profile=app down
